services:
    db:
        container_name: db
        image: timescale/timescaledb:latest-pg18
        volumes:
            - ./var/pgdata:/pgdata
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            PGDATA: /pgdata
    mqtt:
        container_name: mqtt
        image: eclipse-mosquitto:alpine
        volumes:
            - ./var/mosquitto:/mosquitto
        command: "mosquitto -c /mosquitto-no-auth.conf"
    z2m:
        container_name: zigbee2mqtt
        image: ghcr.io/koenkk/zigbee2mqtt
        volumes:
            - ./var/z2m:/app/data
            - ./config/z2m/configuration.yaml:/app/data/configuration.yaml
            - /run/udev:/run/udev:ro
        environment:
            TZ: ${TZ}
            Z2M_ONBOARD_NO_SERVER: 1
        devices:
            - ${ZIGBEE_DEV}:/dev/ttyACM0
        group_add:
            - dialout
        depends_on:
            - mqtt
    homeassistant:
        container_name: homeassistant
        image: ghcr.io/home-assistant/home-assistant:stable
        volumes:
            - ./var/ha:/config
            - /etc/localtime:/etc/localtime:ro
            - /run/dbus:/run/dbus:ro
        environment:
            DISABLE_JEMALLOC: true
            TZ: ${TZ}
        devices:
            - ${ZIGBEE_DEV}:/dev/ttyACM0
        group_add:
            - dialout
        depends_on:
            - mqtt
            - z2m
    grafana:
        container_name: grafana
        image: grafana/grafana-enterprise
        user: "0"
        volumes:
            - ./var/grafana:/var/lib/grafana
        environment:
            GF_PLUGINS_PREINSTALL: grafana-clock-panel

secrets:
    firebase_service_account:
        file: ./secrets/firebase-service-account.json
