services:
    caddy:
        container_name: caddy
        image: caddy:alpine
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"
        volumes:
            - ./config/caddy:/etc/caddy
            - ./var/caddy/data:/data
            - ./var/caddy/config:/config
        environment:
            TZ: ${TZ}
            HOSTNAME: ${HOSTNAME}
    db:
        container_name: db
        image: timescale/timescaledb:latest-pg18
        volumes:
            - ./var/pgdata:/pgdata
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            PGDATA: /pgdata
    api:
        container_name: carpark-iot
        build: src/backend
        user: "0"
        environment:
            TZ: ${TZ}
            CONFIG_PATH: /config.toml
            LD_LIBRARY_PATH: /opt/vc/lib

            MQTT__HOST: mqtt://zigbee2mqtt
            DB__HOST: db
            DB__PORT: 5432
            DB__NAME: postgres
            DB__USER: ${DB_USER}
            DB__PASSWORD: ${DB_PASSWORD}
            FIREBASE__API_KEY: ${FIREBASE_API_KEY}
            FIREBASE__AUTH_DOMAIN: ${FIREBASE_AUTH_DOMAIN}
            FIREBASE__DB_URL: ${FIREBASE_DB_URL}
            FIREBASE__STORAGE_BUCKET_URL: ${FIREBASE_STORAGE_BUCKET_URL}
            FIREBASE__AUTH__TYPE: email
            FIREBASE__AUTH__EMAIL: ${FIREBASE_EMAIL}
            FIREBASE__AUTH__PASSWORD: ${FIREBASE_PASSWORD}
        volumes:
            - ./config/carpark:/config.toml
            - /run/udev:/run/udev:ro
            - /opt/vc:/opt/vc:ro
        devices:
            - /dev/vchiq:/dev/vchiq
            - /dev/gpiomem:/dev/gpiomem
            - /dev/mem:/dev/mem
        cap_add:
            - SYS_RAWIO
        depends_on:
            - mqtt
            - z2m
            - db
    mqtt:
        container_name: mqtt
        image: eclipse-mosquitto:alpine
        volumes:
            - ./var/mosquitto:/mosquitto
        command: "mosquitto -c /mosquitto-no-auth.conf"
    z2m:
        container_name: zigbee2mqtt
        image: ghcr.io/koenkk/zigbee2mqtt
        volumes:
            - ./var/z2m:/app/data
            - ./config/z2m/configuration.yaml:/app/data/configuration.yaml
            - /run/udev:/run/udev:ro
        environment:
            TZ: ${TZ}
            Z2M_ONBOARD_NO_SERVER: 1
        devices:
            - ${ZIGBEE_DEV}:/dev/ttyACM0
        group_add:
            - dialout
        depends_on:
            - mqtt
    homeassistant:
        container_name: homeassistant
        image: ghcr.io/home-assistant/home-assistant:stable
        volumes:
            - ./var/ha:/config
            - /etc/localtime:/etc/localtime:ro
            - /run/dbus:/run/dbus:ro
        environment:
            DISABLE_JEMALLOC: true
            TZ: ${TZ}
        devices:
            - ${ZIGBEE_DEV}:/dev/ttyACM0
        group_add:
            - dialout
        depends_on:
            - mqtt
            - z2m
    grafana:
        container_name: grafana
        image: grafana/grafana-enterprise
        user: "0"
        volumes:
            - ./var/grafana:/var/lib/grafana
        environment:
            GF_SERVER_ROOT_URL: grafana.${HOSTNAME}
            GF_PLUGINS_PREINSTALL: grafana-clock-panel
