[project]
name = "carpark-iot-backend"
version = "0.1.0"
description = ""
requires-python = ">=3.14"
dependencies = [
    "carpark-iot-core",
    "carpark-iot-api",
    "carpark-iot-mqtt"
]
license = { text = "MIT License" }
readme = "README.md"

[tool.uv.sources]
carpark-iot-core = { workspace = true }
carpark-iot-api = { workspace = true }
carpark-iot-mqtt = { workspace = true }

[tool.uv.workspace]
members = [
    "core",
    "api",
    "mqtt"
]
