version: 5
permit_join: true
serial:
    port: /dev/ttyUSB0
    baudrate: 115200
    adapter: ember
    rtscts: false
mqtt:
    server: mqtt://mqtt
    base_topic: zigbee2mqtt
advanced:
    channel: 11
    network_key: GENERATE
    pan_id: GENERATE
    ext_pan_id: GENERATE
frontend:
    enabled: true
homeassistant:
    enabled: true
