[project]
name = "carpark-iot-api"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]",
    "python-multipart",
    "pydantic-settings",
    "jinja2",
    "dependency-injector",
    "carpark-iot-core"
]

[project.scripts]
carpark-iot-api = "carpark_iot_api.application:create_app"

[build-system]
requires = ["uv_build>=0.9.21,<0.10.0"]
build-backend = "uv_build"